apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: a5fde99889c5.ngrok.io
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https     
